# Generated by Django 5.1.3 on 2024-11-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FGFPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("thumbnail", models.CharField(blank=True, max_length=255, null=True)),
                ("post_flair", models.CharField(blank=True, max_length=255, null=True)),
                ("reddit_id", models.CharField(max_length=30)),
                (
                    "direct_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
