# Generated by Django 5.1.3 on 2024-11-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fgfpost",
            name="nsfw",
            field=models.BooleanField(default=False),
        ),
    ]
